[versions]
agp = "9.2.1"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"
androidx-activityCompose = "1.9.3"
androidx-core-ktx = "1.15.0"
compose-plugin = "1.11.1"
haze = "1.0.2"
kotlin = "2.4.10"

[libraries]
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }